CREATE OR REPLACE PACKAGE TEACHER_tapi
IS
type TEACHER_tapi_rec
IS
  record
  (
    TEACHER_ID TEACHER.TEACHER_ID%type ,
    TEACHER_LAST_NAME TEACHER.TEACHER_LAST_NAME%type ,
    SALARY TEACHER.SALARY%type ,
    TEACHER_FIRST_NAME TEACHER.TEACHER_FIRST_NAME%type );
type TEACHER_tapi_tab
IS
  TABLE OF TEACHER_tapi_rec;
  -- insert
  PROCEDURE ins(
      p_TEACHER_ID         IN TEACHER.TEACHER_ID%type ,
      p_TEACHER_LAST_NAME  IN TEACHER.TEACHER_LAST_NAME%type ,
      p_SALARY             IN TEACHER.SALARY%type ,
      p_TEACHER_FIRST_NAME IN TEACHER.TEACHER_FIRST_NAME%type );
  -- update
  PROCEDURE upd(
      p_TEACHER_ID         IN TEACHER.TEACHER_ID%type ,
      p_TEACHER_LAST_NAME  IN TEACHER.TEACHER_LAST_NAME%type ,
      p_SALARY             IN TEACHER.SALARY%type ,
      p_TEACHER_FIRST_NAME IN TEACHER.TEACHER_FIRST_NAME%type );
  -- delete
  PROCEDURE del(
      p_TEACHER_ID IN TEACHER.TEACHER_ID%type );
END TEACHER_tapi;
/
CREATE OR REPLACE PACKAGE body TEACHER_tapi
IS
  -- insert
  PROCEDURE ins(
      p_TEACHER_ID         IN TEACHER.TEACHER_ID%type ,
      p_TEACHER_LAST_NAME  IN TEACHER.TEACHER_LAST_NAME%type ,
      p_SALARY             IN TEACHER.SALARY%type ,
      p_TEACHER_FIRST_NAME IN TEACHER.TEACHER_FIRST_NAME%type )
  IS
  BEGIN
    INSERT
    INTO TEACHER
      (
        TEACHER_ID ,
        TEACHER_LAST_NAME ,
        SALARY ,
        TEACHER_FIRST_NAME
      )
      VALUES
      (
        p_TEACHER_ID ,
        p_TEACHER_LAST_NAME ,
        p_SALARY ,
        p_TEACHER_FIRST_NAME
      );
  END;
-- update
  PROCEDURE upd
    (
      p_TEACHER_ID         IN TEACHER.TEACHER_ID%type ,
      p_TEACHER_LAST_NAME  IN TEACHER.TEACHER_LAST_NAME%type ,
      p_SALARY             IN TEACHER.SALARY%type ,
      p_TEACHER_FIRST_NAME IN TEACHER.TEACHER_FIRST_NAME%type
    )
  IS
  BEGIN
    UPDATE TEACHER
    SET TEACHER_LAST_NAME = p_TEACHER_LAST_NAME ,
      SALARY              = p_SALARY ,
      TEACHER_FIRST_NAME  = p_TEACHER_FIRST_NAME
    WHERE TEACHER_ID      = p_TEACHER_ID;
  END;
-- del
  PROCEDURE del(
      p_TEACHER_ID IN TEACHER.TEACHER_ID%type )
  IS
  BEGIN
    DELETE FROM TEACHER WHERE TEACHER_ID = p_TEACHER_ID;
  END;
END TEACHER_tapi;